ARG stage=local

FROM node as frontend-build

WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client .
RUN npm run build

FROM nginx:alpine
ARG stage

COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY  "nginx/nginx-${stage}.conf" /etc/nginx/nginx.conf


EXPOSE 80