ARG stage=local
ARG mongo

FROM node
ARG stage
ARG mongo

WORKDIR /usr/src/app
COPY server/package*.json ./
RUN npm install
RUN npm install -g ts-node

COPY server/src .

EXPOSE 3001
EXPOSE 3002

ENV MONGO_URI=${mongo}
ENV STAGE=${stage}

CMD ["ts-node", "index.ts"]