version: '3.0'

services:
  frontend:
    image: ${DOCKER_REGISTRY}/medisync:frontend
    container_name: frontend
    build:
      context: .
      dockerfile: client/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network

  backend:
    image: ${DOCKER_REGISTRY}/medisync:backend
    container_name: backend
    build:
      context: .
      dockerfile: server/Dockerfile.backend
    expose:
      - "3001"
      - "3002"
    depends_on:
      - mongodb
      - solver
    networks:
      - network

  solver:
    image: ${DOCKER_REGISTRY}/medisync:backend
    container_name: solver
    build:
      context: .
      dockerfile: solver/Dockerfile.solver
    expose:
      - "5000"
    networks:
      - network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network: