FROM node as frontend-build

WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client .
RUN npm run build

FROM nginx:alpine


COPY --from=frontend-build /app/dist /usr/share/nginx/html

EXPOSE 80