version: '3.0'

services:
  frontend:
    image: ${DOCKER_REGISTRY}/medisync:frontend
    container_name: frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network

  backend:
    image: ${DOCKER_REGISTRY}/medisync:backend
    container_name: backend
    environment:
      - STAGE=prod
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "3001"
      - "3002"
    networks:
    - network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network: