#!/bin/sh
# This script is run by Husky before every commit.
# It will lint your code using ESLint.

# Run ESLint for frontend
(cd client && npm run lint) || exit 1

# Run ESLint for backend
(cd server && npm run lint) || exit 1