name: Deploy to AWS ECS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION : "us-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          role-to-assume: arn:aws:iam::125308813332:role/medisync-deploy-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws_default_region: us-east-1

          aws_elb_app_port: 8080